# Wire up travis
language: python
sudo: false

python:
  - "3.6"
  - "3.7"

before_install:
  - sudo apt-get install openslide-tools

# command to install dependencies
install:
  - pip install -e .[testing]
  - pip install flake8

# command to run tests
script:
  - flake8 .
  - pytest --mpl --cov=src.histolab

after_success:
  - coveralls

notifications:
  slack: mpba:fBrjUWlUSa3XKeCA8zFsTFu2